# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
fail_fast: false
default_language_version:
    python: python3
default_stages:
-   commit
-   push
minimum_pre_commit_version: 3.0.0
repos:
-   repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
    -   id: black
        additional_dependencies: [toml]
-   repo: https://github.com/timothycrosley/isort
    rev: 5.12.0
    hooks:
    -   id: isort
        additional_dependencies: [toml]
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: check-docstring-first
    -   id: end-of-file-fixer
    -   id: check-added-large-files
    -   id: mixed-line-ending
    -   id: trailing-whitespace
        exclude: ^.bumpversion.cfg$
    -   id: check-merge-conflict
    -   id: check-case-conflict
    -   id: check-symlinks
    -   id: check-yaml
    -   id: check-ast
    -   id: requirements-txt-fixer
-   repo: https://github.com/pycqa/flake8
    rev: 6.0.0
    hooks:
    -   id: flake8
        additional_dependencies: [flake8-docstrings, flake8-comprehensions, flake8-bugbear]
-   repo: https://github.com/asottile/blacken-docs
    rev: 1.13.0
    hooks:
    -   id: blacken-docs
        additional_dependencies: [black]
-   repo: https://github.com/asottile/pyupgrade
    rev: v3.4.0
    hooks:
    -   id: pyupgrade
        args: [--py3-plus, --py36-plus]
-   repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
    rev: v2.9.0
    hooks:
    -   id: pretty-format-yaml
        args: [--autofix, --indent, '4']
-   repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.10.0
    hooks:
    -   id: python-no-eval
    -   id: python-use-type-annotations
    -   id: python-check-blanket-noqa
    -   id: rst-backticks
    -   id: rst-directive-colons
    -   id: rst-inline-touching-normal
