# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
fail_fast: false
default_language_version:
    python: python3
default_stages:
-   commit
-   push
minimum_pre_commit_version: 2.7.1
repos:
-   repo: https://github.com/psf/black
    rev: 21.6b0
    hooks:
    -   id: black
        additional_dependencies: [toml]
-   repo: https://github.com/timothycrosley/isort
    rev: 5.9.1
    hooks:
    -   id: isort
        additional_dependencies: [toml]
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
    -   id: check-docstring-first
    -   id: end-of-file-fixer
    -   id: check-added-large-files
    -   id: mixed-line-ending
    -   id: trailing-whitespace
        exclude: ^.bumpversion.cfg$
    -   id: check-merge-conflict
    -   id: check-case-conflict
    -   id: check-symlinks
    -   id: check-yaml
    -   id: check-ast
    -   id: fix-encoding-pragma
        args: [--remove] # for Python3 codebase, it's not necessary
    -   id: requirements-txt-fixer
-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.2
    hooks:
    -   id: flake8
        additional_dependencies: [flake8-docstrings, flake8-comprehensions, flake8-bugbear]
-   repo: https://github.com/myint/rstcheck
    rev: 3f92957478422df87bd730abde66f089cc1ee19b
    hooks:
    -   id: rstcheck
-   repo: https://github.com/asottile/blacken-docs
    rev: v1.10.0
    hooks:
    -   id: blacken-docs
        additional_dependencies: [black==20.8b1]
-   repo: https://github.com/asottile/pyupgrade
    rev: v2.20.0
    hooks:
    -   id: pyupgrade
        args: [--py3-plus, --py36-plus]
-   repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
    rev: v2.1.0
    hooks:
    -   id: pretty-format-yaml
        args: [--autofix, --indent, '4']
-   repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.9.0  # Use the ref you want to point at
    hooks:
    -   id: python-no-eval
    -   id: python-use-type-annotations
    -   id: python-check-blanket-noqa
    -   id: rst-backticks
    -   id: rst-directive-colons
    -   id: rst-inline-touching-normal
