name: Lint

on:
    schedule:
    -   cron: 00 00 * * 1  # every Monday at 00:00
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
        -   uses: actions/checkout@v4
        -   name: Set up Python 3.11
            uses: actions/setup-python@v5
            with:
                python-version: '3.11'

        -   uses: actions/cache@v4
            with:
                path: ~/.cache/pre-commit
                key: precommit-${{ env.pythonLocation }}-${{ hashFiles('**/.pre-commit-config.yaml') }}

        -   name: Install dependencies
            run: |
                python -m pip install --upgrade pip
                pip install tox

        -   name: Lint
            run: |
                tox -e lint
