name: Lint

on:
    schedule:
    -   cron: 00 00 * * 1  # every Monday at 00:00
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
        -   uses: actions/checkout@v4
        -   name: Set up Python 3.13
            uses: actions/setup-python@v5
            with:
                python-version: '3.13'

        -   name: Install uv
            uses: astral-sh/setup-uv@v5
            with:
                enable-cache: true

        -   name: Set up Python ${{ matrix.python }}
            run: uv python install ${{ matrix.python-version }}

        -   name: Install dependencies
            run: |
                uv sync --all-extras

        -   uses: actions/cache@v4
            with:
                path: ~/.cache/pre-commit
                key: precommit-${{ env.pythonLocation }}-${{ hashFiles('**/.pre-commit-config.yaml') }}

        -   name: Lint
            run: |
                uv run tox -e lint
